[API]
Host = "127.0.0.1"
Port = 7000
Token = "A0473A67-27A1-3C05-A2D1-5C134639347F"

[NDTP]
Host = "79.104.55.66"
Port = 7070

[System]
LogDir = "/data/NDTPClient/log/tns-client.log"
MessageLogDir = "/data/NDTPClient/log/tns-MessageLog.log"
Timeout = 10
PeerAddr = 706197201
Regular = true
Disconnect = false
Interval = 30
ServerPort = 4054

[History]
HistDir = "/data/NDTPClient/db/tns-hist.db"
MaxRecords = 150000
CleanInterval = 20
